FROM docker.io/library/node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY frontend ./frontend
RUN npm run build

FROM docker.io/library/caddy:alpine
COPY --from=builder /app/frontend/dist /srv
COPY frontend/Caddyfile /etc/caddy/Caddyfile
EXPOSE 80
